# Generated by Django 6.0.5 on 2026-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=20)),
                ('choice', models.CharField(choices=[('industrial_visit', 'Industrial Visit'), ('tech_viva', 'Technology Viva Presentation')], max_length=50)),
                ('viva_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
