# Generated by Django 6.0.5 on 2026-05-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Form title shown to users', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description shown below the title')),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active forms accept submissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.dynamicform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The question text', max_length=300)),
                ('field_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Paragraph'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='short_text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for Dropdown/Checkbox (e.g. "Option A, Option B, Option C")')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='activities.dynamicform')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='activities.dynamicsubmission')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.formfield')),
            ],
        ),
    ]
